config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  patch '/businesses/:id' => 'businesses#update', as: :business_update

  get '/business/deals' => 'deals#index', as: :index
  post '/business/:id/deals/new' => 'deals#create', as: :create
  get '/business/:id/deals/new' => 'deals#new', as: :deal_new
  get '/business/deals/:id/edit' => 'deals#edit', as: :deal_edit
  patch '/business/deals/:id/edit' => 'deals#update', as: :deal_update
  delete 'business/deals/:id' => 'deals#destroy', as: :deal_delete
  get 'business/deals/:id/show' => 'deals#show', as: :deal_show

  resources :businesses

  resources :lists
  

  root 'sessions#index'
  

  get 'users/new' => 'users#new', as: :users_new
  post 'users/new' => 'users#create'
  get 'users/:id' => 'users#show', as: :user
  patch '/users/:id' => 'users#edit', as: :update_user
  get '/sessions' => 'sessions#index', as: :sessions
  get '/users' => 'users#index', as: :user_index   # Newly added
  get 'sessions/business_index/', :to => 'sessions#business_index', as: :business_index
  get 'sessions/settings/', :to => 'sessions#settings', as: :settings
  get '/signin', to: 'sessions#new', as: :sessions_new
  post '/signin', to: 'sessions#create', as: :sign_in
  delete '/sessions' => 'sessions#destroy', as: :sign_out
  delete '/users/:id' => 'sessions#destroy', as: :log_out

  scope '/api' do
    resources :users, defaults: {format: 'json'}
  end

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  attr_reader :password
  attr_accessor :email_confirmation
  attr_accessor :password_confirmation

  has_one :list
  belongs_to :business

  before_create :set_default_values, :only => :create
  
  validates_uniqueness_of :email, on: :create
  validates_presence_of :email, :email_confirmation, on: :create
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, on: :create 
  validates :password, presence: true, confirmation: true, length: { minimum: 7 }, format: { with: /\S{7}/}, on: :create
  # validates :first_name, presence: true, confirmation: true, format: { with: /[a-zA-Z]\[:space:\]/}, on: :create
  # validates :last_name, presence: true, confirmation: true, format: { with: /[a-zA-Z]\[:space:\]/}, on: :create
  
  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
    if BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end

  def set_default_values
    self.customer = true if self.customer == nil
    self.business_owner = false if self.business_owner == nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include SessionsHelper
respond_to :json, :html

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :email, :email_confirmation, :password, :password_confirmation, :business_owner, :customer))
	  if @user.save && @user.business_owner == true
      log_in(@user)
      redirect_to new_business_path
    elsif @user.save && @user.business_owner == false
      log_in(@user)
      redirect_to sessions_path
    elsif @user.errors.messages[:password] && @user.errors.messages[:email] 
	    @user.email = ""
	    @user.email_confirmation = ""
	    @user.password = ""
	    @user.password_confirmation = ""
	    render 'new'
    elsif @user.errors.messages[:email] || @user.errors.messages[:email_confirmation]
	    @user.email  = ""
	    @user.email_confirmation = ""
      render 'new'
    elsif @user.errors.messages[:password] || @user.errors.messages[:password_confirmation]
	    @user.password = ""
	    @user.password_confirmation = ""
	    render 'new'
    else
	    render 'new'
    end
  end

  def edit
   @user = User.find(params[:id])
  end
   
  def show
    @user = User.find(params[:id])
    respond_with @user
  end

  def update
    @user = User.find(params[:id])
    if @user.business.update(params.require(:user).permit(:business_owner, :first_name, :last_name, :email, :password))
      redirect_to sessions_path(@user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if @user.customer == true %>
	<%= render 'layouts/customernav' %>
<% end %>

app/views/users/new.html.erb
<div class= "users-new">

<header class="users-header">
  <h1 class="signup-header">Welcome to GeoDeals</h1>
</header>

<main class="users-new-container">

  <div class="sign-up">
  	
    <%= form_for @user, url: users_new_path do |u| %>

       	<div class="business-check-box">
       	<%= u.check_box :business_owner %>
   		</div>
			
			<form>
				<div class="row">
					<div class="large-12 columns">
			   			<%= u.text_field :first_name, :class => @user.errors.messages[:first_name] ? 'new-user-forms' : 'new-user-forms', :placeholder => @user.errors.messages[:first_name] ? "First Name #{@user.errors.messages[:first_name].join(" & ")}" : "First Name" %>
			   		</div>
			   	</div>

				<div class="row">
					<div class="large-12 columns">
			   			<%= u.text_field :last_name, :class => @user.errors.messages[:last_name] ? 'new-user-forms' : 'new-user-forms', :placeholder => @user.errors.messages[:last_name] ? "Last Name #{@user.errors.messages[:last_name].join(" & ")}" : "Last Name" %>
			   		</div>
			   	</div>

				<div class="row">
					<div class="large-12 columns">
			   			<%= u.text_field :email, :class => @user.errors.messages[:email] ? 'new-user-forms' : 'new-user-forms', :placeholder => @user.errors.messages[:email] ? "Email #{@user.errors.messages[:email].join(" & ")}" : "Email" %>
			   		</div>
			   	</div>

				<div class="row">
					<div class="large-12 columns">
			   			<%= u.text_field :email_confirmation, :class => @user.errors.messages[:email_confirmation] ? 'new-user-forms' : 'new-user-forms', :placeholder => @user.errors.messages[:email_confirmation] ? "Email Confirmation #{@user.errors.messages[:email_confirmation].join(" & ")}" : "Email Confirmation" %>
			   		</div>
			   	</div>

				<div class="row">
					<div class="large-12 columns">
			   			<%= u.password_field :password, :class => @user.errors.messages[:password] ? 'new-user-forms' : 'new-user-forms', :placeholder => @user.errors.messages[:password] ? "Password #{@user.errors.messages[:password].join(" & ")}" : "Password" %>
			   		</div>	
			   	</div>

				<div class="row">
					<div class="large-12 columns">
			   			<%= u.password_field :password_confirmation, :class => @user.errors.messages[:password_confirmation] ? 'new-user-forms' : 'new-user-forms', :placeholder => @user.errors.messages[:password_confirmation] ? "Password Confirmation #{@user.errors.messages[:password_confirmation].join(" & ")}" : "Password Confirmation" %>
			   		</div>
			   	</div>
			
			
			<div class="signup-submit">
		   	<%= u.submit "Sign Up", :class => 'button radius signup-btn'%>
		   	</div></br>
			</form>
		   	<%= link_to "Returning? Sign In", sign_in_path, :class=> "return-to-signin" %>
		   	

    <% end %>


  </div>
</main>

app/views/users/show.html.erb
<h1>USER SHOW PAGE (test)</h1>

<h1><%= @user.first_name %></h1>
<h1><%= @user.last_name %></h1>

<h2>User details</h2>