config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  patch '/businesses/:id' => 'businesses#update', as: :business_update

  get '/business/deals' => 'deals#index', as: :index
  post '/business/:id/deals/new' => 'deals#create', as: :create
  get '/business/:id/deals/new' => 'deals#new', as: :deal_new
  get '/business/deals/:id/edit' => 'deals#edit', as: :deal_edit
  patch '/business/deals/:id/edit' => 'deals#update', as: :deal_update
  delete 'business/deals/:id' => 'deals#destroy', as: :deal_delete
  get 'business/deals/:id/show' => 'deals#show', as: :deal_show

  resources :businesses

  resources :lists
  

  root 'sessions#index'
  

  get 'users/new' => 'users#new', as: :users_new
  post 'users/new' => 'users#create'
  get 'users/:id' => 'users#show', as: :user
  patch '/users/:id' => 'users#edit', as: :update_user
  get '/sessions' => 'sessions#index', as: :sessions
  get '/users' => 'users#index', as: :user_index   # Newly added
  get 'sessions/business_index/', :to => 'sessions#business_index', as: :business_index
  get 'sessions/settings/', :to => 'sessions#settings', as: :settings
  get '/signin', to: 'sessions#new', as: :sessions_new
  post '/signin', to: 'sessions#create', as: :sign_in
  delete '/sessions' => 'sessions#destroy', as: :sign_out
  delete '/users/:id' => 'sessions#destroy', as: :log_out

  scope '/api' do
    resources :users, defaults: {format: 'json'}
  end

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :business
  has_many :users, through: :lists

  before_create :set_deal_salt
  # validate :start_date_not_less_than_today
  # validate :end_date_not_less_than_today
  # validates_presence_of :name, :description, :fine, :start_date, :end_date, on: :create
  # validates :code, format: { with: /[0-9]+{11}/}, on: :create
  
  def set_deal_salt
    self.code = (0...10).map { ('1'..'50').to_a[rand(26)] }.join
  end

  # def start_date_not_less_than_today
  # 	if self.start_date < Date.today
  # 		errors.add(:start_date, "That date is in the past!")
  # 	end
  # end

  # def end_date_not_less_than_today
  # 	if self.end_date < Date.today
  # 		errors.add(:start_date, "That date is in the past!")
  # 	end
  # end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
include SessionsHelper
  def index
    @user = current_user
  	@deals = Deal.all
  end

  def destroy
    deal_record = Deal.find(params[:id])
    deal_record.destroy
    redirect_to business_index_path
  end

  def edit
  	@deal = Deal.find(params[:id])
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(params.require(:deal).permit(:name, :description, :fine, :start_date, :end_date, :start_time, :end_time, :business_id, :latitude, :longitude, :start_datetime, :end_datetime))
      curr_user_biz_id = current_user.business_id
      curr_user_biz_obj = Business.find_by_id(curr_user_biz_id)
      curr_user_biz_lat = curr_user_biz_obj.latitude
      curr_user_biz_lng = curr_user_biz_obj.longitude
      @deal.business_id = curr_user_biz_id
      @deal.latitude = curr_user_biz_lat
      @deal.longitude = curr_user_biz_lng
      @deal.save
      if @deal.save
        redirect_to business_index_path
      else
        render 'new'
      end
  end

  def show
    @deal = Deal.find(params[:id])
  end

  def update
    redirect_to index_path
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/edit.html.erb
<h1>Edit</h1>

<%= form_for @deal, url: deal_edit_path do |d| %>

	<%= d.label :name %>
	<%= d.text_field :name %>

	<%= d.label :description %>
	<%= d.text_area :description, size: "50x10" %>

	<%= d.label :fine %>
	<%= d.text_area :fine, size: "50x10" %>

	<%= d.label :start_date %>
	<%= d.date_select :start_date %>

	<%= d.label :end_date %>
	<%= d.date_select :end_date %>

	<%= d.submit "submit update" %>

<% end %>


<%= link_to "Go Back", index_path %>

app/views/deals/index.html.erb
<h1>Welcome Business Name</h1>

<!-- This section is an overview of all the deals for the business -->

<h2>Current Deal Campaigns</h2>

<% @deals.each do |deal| %>

<div id="individualDeals">

	<%= deal.name %></br>
	<%= deal.description %></br>
	<%= deal.fine %></br>
	<%= deal.start_date %></br>
	<%= deal.end_date %></br>

	<%= link_to "Edit", deal_edit_path(deal) %>
	<%= link_to "Delete", deal_delete_path(deal), method: :delete %>
	<%= link_to "Show", deal_show_path(deal) %>

</div>

<% end %></br>

<%= link_to "Create a new deal", deal_new_path %>

app/views/deals/new.html.erb
<h1 class="new-deals-header">CREATE A NEW DEAL</h1>

<!-- This begins the section for the business to enter the details for their deal -->

<div class="new-deals-container">
<%= form_for(@deal, url: create_path, method: :post) do |d| %>
	<h3>Name of the deal</h3>
	<p>This should be descriptive but short.</p>
	<p>Example: "Buy one get one"</p>
		<div class="row">
		<%= d.text_field :name, :class => "large-4 columns" %>
		</div>
		
	<h3>Deal details</h3>
	<p>Provide details for the deal you are offering. Optimal length is a tweet! (140 characters).</p>
		<div class="row">
		<%= d.text_field :description, :class => "large-4 columns"  %>
		</div>

	<h3>Fine print</h3>
	<p>Provide the stipulations for this deal.</p>
		<div class="row">
		<%= d.text_field :fine, :class => "large-4 columns" %>
		</div>
				
	<h3>START Date and Time</h3>
	<p>Select the date and time this deal will start</p>
		<div class="row">
		<%= d.date_select :start_date, :class => "large-4 columns" %>
		</div>

	<h3>END Date</h3>
	<p>Select date deal will end</p>
		<div class="row">
		<%= d.date_select :end_date, :class => "large-4 columns" %>
		</div>

	<div class="submit-deal-button">
	<%= d.submit "Submit" %>
	</div>
		
<% end %>
</div>


<%= link_to "Go back", sessions_path, :class => "new-deals-back" %>

app/views/deals/show.html.erb
<script src="http://d3js.org/d3.v3.min.js"></script>

<h1><%= @deal.name %></h1>
<h2>Performance details</h2>
<%= link_to "Go back", index_path %>

<svg class="chart"></svg>




<!--


<script>

var margin = {top: 20, right: 30, bottom: 30, left: 40},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

var x = d3.scale.ordinal()
    .rangeRoundBands([0, width], .1);

var y = d3.scale.linear()
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left");

var chart = d3.select(".chart")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

d3.tsv("public/data/data.tsv", type, function(error, data) {
  x.domain(data.map(function(d) { return d.name; }));
  y.domain([0, d3.max(data, function(d) { return d.value; })]);

  chart.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis);

  chart.append("g")
      .attr("class", "y axis")
      .call(yAxis);

  chart.selectAll(".bar")
      .data(data)
    .enter().append("rect")
    .attr("class", "bar")
      .attr("x", function(d) { return x(d.name); })
      .attr("y", function(d) { return y(d.value); })
      .attr("height", function(d) { return height - y(d.value); })
      .attr("width", x.rangeBand());
});

function type(d) {
  d.value = +d.value; // coerce to number
  return d;
}

// NEW SECTION

var width = 1500,
    height = 1200;

var k = 10; // number of candidates to consider per circle

var quadtree = d3.geom.quadtree()
    .extent([[0, 0], [width, height]])
    ([[Math.random() * width, Math.random() * height]]);

var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height);

var gCandidate = svg.append("g")
    .attr("class", "candidate");

var gPoint = svg.append("g")
    .attr("class", "point");

gPoint.append("circle")
    .attr("r", 3.5)
    .attr("cx", quadtree.point[0])
    .attr("cy", quadtree.point[1]);

(function nextPoint() {
  var i = 0,
      maxDistance = -Infinity,
      bestCandidate = null;

  (function nextCandidate() {
    if (++i > k) {
      gCandidate.selectAll("*").transition()
          .style("opacity", 0)
          .remove();

      gPoint.append("circle")
          .attr("r", 3.5)
          .attr("cx", bestCandidate.__data__[0])
          .attr("cy", bestCandidate.__data__[1]);

      quadtree.add(bestCandidate.__data__);

      return nextPoint();
    }

    var x = Math.random() * width,
        y = Math.random() * height,
        closest = search(x, y),
        dx = closest[0] - x,
        dy = closest[1] - y,
        distance = Math.sqrt(dx * dx + dy * dy);

    var g = gCandidate.insert("g", "*")
        .datum([x, y])
        .attr("class", "candidate--current");

    g.append("circle")
        .attr("class", "point")
        .attr("r", 3.5)
        .attr("cx", x)
        .attr("cy", y);

    g.append("circle")
        .attr("class", "search")
        .attr("r", 2.5)
        .attr("cx", x)
        .attr("cy", y);

    g.append("line")
        .attr("class", "search")
        .attr("x1", x)
        .attr("y1", y)
        .attr("x2", x)
        .attr("y2", y);

    var t = g.transition()
        .duration(500)
        .each("end", function() {
          if (distance > maxDistance) {
            d3.select(bestCandidate).attr("class", null);
            d3.select(this.parentNode.appendChild(this)).attr("class", "candidate--best");
            bestCandidate = this;
            maxDistance = distance;
          } else {
            d3.select(this).attr("class", null);
          }
          nextCandidate();
        });

    t.select("circle.search")
        .attr("r", distance);

    t.select("line.search")
        .attr("x2", closest[0])
        .attr("y2", closest[1]);
  })();

})();

// Find the closest node to the specified point.
function search(x, y) {
  var x0 = 0,
      y0 = 0,
      x3 = width,
      y3 = width,
      minDistance2 = Infinity,
      closestPoint;

  (function find(node, x1, y1, x2, y2) {
    var point;

    // stop searching if this cell can’t contain a closer node
    if (x1 > x3 || y1 > y3 || x2 < x0 || y2 < y0) return;

    // visit this point
    if (point = node.point) {
      var dx = x - point[0],
          dy = y - point[1],
          distance2 = dx * dx + dy * dy;
      if (distance2 < minDistance2) {
        var distance = Math.sqrt(minDistance2 = distance2);
        x0 = x - distance, y0 = y - distance;
        x3 = x + distance, y3 = y + distance;
        closestPoint = point;
      }
    }

    // bisect the current node
    var children = node.nodes,
        xm = (x1 + x2) * .5,
        ym = (y1 + y2) * .5,
        right = x > xm,
        below = y > ym;

    // visit closest cell first
    if (node = children[below << 1 | right]) find(node, right ? xm : x1, below ? ym : y1, right ? x2 : xm, below ? y2 : ym);
    if (node = children[below << 1 | !right]) find(node, right ? x1 : xm, below ? ym : y1, right ? xm : x2, below ? y2 : ym);
    if (node = children[!below << 1 | right]) find(node, right ? xm : x1, below ? y1 : ym, right ? x2 : xm, below ? ym : y2);
    if (node = children[!below << 1 | !right]) find(node, right ? x1 : xm, below ? y1 : ym, right ? xm : x2, below ? ym : y2);
  })(quadtree, x0, y0, x3, y3);

  return closestPoint;
}

</script>


-->

app/views/deals/show1.html.erb
<html>
<head>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvQPK_z7tyIdBpGxui6Jps_zZsPudqzJ4&libraries=geometry"> </script>

<!--<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?libraries=geometry"></script>-->

<script type="text/javascript">

var mapStyle = [{"featureType":"landscape","stylers":[{"hue":"#FFA800"},{"saturation":0},{"lightness":0},{"gamma":1}]},{"featureType":"road.highway","stylers":[{"hue":"#53FF00"},{"saturation":-73},{"lightness":40},{"gamma":1}]},{"featureType":"road.arterial","stylers":[{"hue":"#FBFF00"},{"saturation":0},{"lightness":0},{"gamma":1}]},{"featureType":"road.local","stylers":[{"hue":"#00FFFD"},{"saturation":0},{"lightness":30},{"gamma":1}]},{"featureType":"water","stylers":[{"hue":"#00BFFF"},{"saturation":6},{"lightness":8},{"gamma":1}]},{"featureType":"poi","stylers":[{"hue":"#679714"},{"saturation":33.4},{"lightness":-25.4},{"gamma":1}]}];

function initialize() {
	var mapOptions = {
	   center : {
				lat: 34.0214935,
				lng: -118.4806145
				},
		zoom: 8,
		styles: mapStyle
	};


///////////////////////////  DISTANCE BETWEEN 2 LOCATIONS  /////////////////////////////
  var loc1 = {lat: 34.0218628, lng: -118.4804206};
  var loc2 = {lat: 33.8336391, lng: -118.3511089};

  var distance = google.maps.geometry.spherical.computeDistanceBetween(new google.maps.LatLng(loc1.lat, loc1.lng), new google.maps.LatLng(loc2.lat, loc2.lng));

  document.getElementById('calculation').innerHTML = distance*0.00062 + ' miles';


////////////////////////////  ALL DEALS DISPLAYED ON MAP  //////////////////////////////
  var map = new google.maps.Map(document.getElementById('map'), mapOptions);

  mapPoints = [<% @deal.each do |mp| %>
  	{latitude: <%= mp.latitude %>, longitude: <%= mp.longitude %>},<% end %>];

  for(var i = 0; i < mapPoints.length; ++i)
  {
	  var someCoolPlace = new google.maps.LatLng(mapPoints[i].latitude, mapPoints[i].longitude);
	  var marker = new google.maps.Marker({
	    position: someCoolPlace,
	    title: 'Deal $$!',
	    map: map,
	    animation: google.maps.Animation.BOUNCE,
	    icon: "/assets/nampng.png",
	    draggable: true
	  });
	}
}

 //  navigator.geolocation.getCurrentPosition(latitude);
 //  navigator.geolocation.getCurrentPosition(longitude);
 //  function latitude(pos) {
 //    var curr = pos.coords;
 //      document.getElementById('currentLat').innerHTML = curr.latitude
	// };
 //  function longitude(pos) {
 //  	var curr = pos.coords;
 //      document.getElementById('currentLng').innerHTML = curr.longitude
	// };	
  
 //  latitude(pos);
 //  longitude(pos);

////// var x = document.getElementById("demo");



///////////////////////////  FUNCTION INITIALIZER ON LOAD  ///////////////////////////
google.maps.event.addDomListener(window, 'load', initialize, getLocation);


//////////////////////  USER'S CURRENT POSITION & DISTANCE FROM /////////////////////
function showPosition(position) {
    document.getElementById("currentLat").innerHTML = position.coords.latitude;	
    document.getElementById("currentLng").innerHTML = position.coords.longitude;
    //var loc3 = {lat: 33.8336391, lng: -118.3511089};
   

	var distanceNew = google.maps.geometry.spherical.computeDistanceBetween(new google.maps.LatLng(mapPoints[20].latitude, mapPoints[20].longitude), new google.maps.LatLng(position.coords.latitude, position.coords.longitude));

	///////  CONSOLE.LOG EACH MAP POINT IN DB  ///////
	for(var i = 0; i < mapPoints.length; ++i) 
	{console.log(new google.maps.LatLng(mapPoints[i].latitude, mapPoints[i].longitude))};

	document.getElementById('newCalculation').innerHTML = distanceNew*0.00062 + ' miles';
}

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else { 
        document.getElementById("currentLat").innerHTML = "Geolocation is not supported by this browser.";
    }
}

getLocation();


</script>

<style type="text/css">
	
#map {
	height: 605px;
	width: 1100px;
	margin: 0 auto;
	border: 10px solid white;
	box-shadow: 0px 0px 40px 10px #ccc;

}

.container {
	margin-top: 35px;
}

</style>

</head>


<body>

<div class="container">

<h2 class="p-heading">An exhuastive list of deals</h2>
<p id="calculation"></p>
<p id="currentLat"></p>
<p id="currentLng"></p>
<p id="newCalculation"></p>

<div id="map">Map!</div>

</body>
</html>

app/views/deals/show2.html.erb
<html>
<head>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvQPK_z7tyIdBpGxui6Jps_zZsPudqzJ4&libraries=geometry"> </script>

<!--<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?libraries=geometry"></script>-->

<script type="text/javascript">

var mapStyle = [{"featureType":"landscape","stylers":[{"hue":"#FFA800"},{"saturation":0},{"lightness":0},{"gamma":1}]},{"featureType":"road.highway","stylers":[{"hue":"#53FF00"},{"saturation":-73},{"lightness":40},{"gamma":1}]},{"featureType":"road.arterial","stylers":[{"hue":"#FBFF00"},{"saturation":0},{"lightness":0},{"gamma":1}]},{"featureType":"road.local","stylers":[{"hue":"#00FFFD"},{"saturation":0},{"lightness":30},{"gamma":1}]},{"featureType":"water","stylers":[{"hue":"#00BFFF"},{"saturation":6},{"lightness":8},{"gamma":1}]},{"featureType":"poi","stylers":[{"hue":"#679714"},{"saturation":33.4},{"lightness":-25.4},{"gamma":1}]}];

function initialize() {
	var mapOptions = {
	   center : {
				lat: 34.0214935,
				lng: -118.4806145
				},
		zoom: 8,
		styles: mapStyle
	};


///////////////////////////  DISTANCE BETWEEN 2 LOCATIONS  /////////////////////////////
  var loc1 = {lat: 34.0218628, lng: -118.4804206};
  var loc2 = {lat: 33.8336391, lng: -118.3511089};

  var distance = google.maps.geometry.spherical.computeDistanceBetween(new google.maps.LatLng(loc1.lat, loc1.lng), new google.maps.LatLng(loc2.lat, loc2.lng));

  document.getElementById('calculation').innerHTML = distance*0.00062 + ' miles';


////////////////////////////  ALL DEALS DISPLAYED ON MAP  //////////////////////////////
  var map = new google.maps.Map(document.getElementById('map'), mapOptions);

  mapPoints = [<% @deal.each do |mp| %>
  	{latitude: <%= mp.latitude %>, longitude: <%= mp.longitude %>},<% end %>];

  for(var i = 0; i < mapPoints.length; ++i)
  {
	  var someCoolPlace = new google.maps.LatLng(mapPoints[i].latitude, mapPoints[i].longitude);
	  var marker = new google.maps.Marker({
	    position: someCoolPlace,
	    title: 'Deal $$!',
	    map: map,
	    animation: google.maps.Animation.BOUNCE,
	    icon: "/assets/nampng.png",
	    draggable: true
	  });
	}
}

 //  navigator.geolocation.getCurrentPosition(latitude);
 //  navigator.geolocation.getCurrentPosition(longitude);
 //  function latitude(pos) {
 //    var curr = pos.coords;
 //      document.getElementById('currentLat').innerHTML = curr.latitude
	// };
 //  function longitude(pos) {
 //  	var curr = pos.coords;
 //      document.getElementById('currentLng').innerHTML = curr.longitude
	// };	
  
 //  latitude(pos);
 //  longitude(pos);

////// var x = document.getElementById("demo");



///////////////////////////  FUNCTION INITIALIZER ON LOAD  ///////////////////////////
google.maps.event.addDomListener(window, 'load', initialize, getLocation);


//////////////////////  USER'S CURRENT POSITION & DISTANCE FROM /////////////////////
function showPosition(position) {
    document.getElementById("currentLat").innerHTML = position.coords.latitude;	
    document.getElementById("currentLng").innerHTML = position.coords.longitude;

	var distanceNew = google.maps.geometry.spherical.computeDistanceBetween(new google.maps.LatLng(mapPoints[20].latitude, mapPoints[20].longitude), new google.maps.LatLng(position.coords.latitude, position.coords.longitude));

///////////////////  CONSOLE.LOG EACH MAP POINT IN DB  ///////////////////
//	for(var i = 0; i < mapPoints.length; ++i) 
//	{console.log(new google.maps.LatLng(mapPoints[i].latitude, mapPoints[i].longitude))};
//	document.getElementById('newCalculation').innerHTML = distanceNew*0.00062 + ' miles';

///////////////// FIND DISTANCE FROM EACH DEAL LOCATION //////////////////
  for(var i = 0; i < mapPoints.length; ++i)
  	{
	console.log(google.maps.geometry.spherical.computeDistanceBetween(new google.maps.LatLng(mapPoints[i].latitude, mapPoints[i].longitude), new google.maps.LatLng(position.coords.latitude, position.coords.longitude)));
  	}


}   /// SHOW POSITION ENDS HERE

//////////////////////////// GET CURRENT LOCATION /////////////////////////////
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else { 
        document.getElementById("currentLat").innerHTML = "Geolocation is not supported by this browser.";
    }
}

getLocation();


</script>

<style type="text/css">
	
#map {
	height: 605px;
	width: 1100px;
	margin: 0 auto;
	border: 10px solid white;
	box-shadow: 0px 0px 40px 10px #ccc;

}

.container {
	margin-top: 35px;
}

</style>

</head>


<body>

<div class="container">

<h2 class="p-heading">An exhuastive list of deals</h2>
<p id="calculation"></p>
<p id="currentLat"></p>
<p id="currentLng"></p>
<p id="newCalculation"></p>

<div id="map">Map!</div>

</body>
</html>

app/views/deals/show3.html.erb
<!DOCTYPE html>
<html> 
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvQPK_z7tyIdBpGxui6Jps_zZsPudqzJ4"></script>

<script>
function showlocation(){
    navigator.geolocation.watchPosition(callback);
}
function callback(position){
    document.getElementById('latitude').innerHTML=position.coords.latitude;
    document.getElementById('longitude').innerHTML=position.coords.longitude;
}
</script>


<body>
Click Show location button and run :)
<input type="button" value="Show Location" onclick="showlocation()"/> 
 
<h3>Lat and Lng!</h3>
<br/>
Latitude: <span id="latitude">..</span> <br>
Longitude: <span id="longitude">..</span>
</body>


</html>