config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  patch '/businesses/:id' => 'businesses#update', as: :business_update

  get '/business/deals' => 'deals#index', as: :index
  post '/business/:id/deals/new' => 'deals#create', as: :create
  get '/business/:id/deals/new' => 'deals#new', as: :deal_new
  get '/business/deals/:id/edit' => 'deals#edit', as: :deal_edit
  patch '/business/deals/:id/edit' => 'deals#update', as: :deal_update
  delete 'business/deals/:id' => 'deals#destroy', as: :deal_delete
  get 'business/deals/:id/show' => 'deals#show', as: :deal_show

  resources :businesses

  resources :lists
  

  root 'sessions#index'
  

  get 'users/new' => 'users#new', as: :users_new
  post 'users/new' => 'users#create'
  get 'users/:id' => 'users#show', as: :user
  patch '/users/:id' => 'users#edit', as: :update_user
  get '/sessions' => 'sessions#index', as: :sessions
  get '/users' => 'users#index', as: :user_index   # Newly added
  get 'sessions/business_index/', :to => 'sessions#business_index', as: :business_index
  get 'sessions/settings/', :to => 'sessions#settings', as: :settings
  get '/signin', to: 'sessions#new', as: :sessions_new
  post '/signin', to: 'sessions#create', as: :sign_in
  delete '/sessions' => 'sessions#destroy', as: :sign_out
  delete '/users/:id' => 'sessions#destroy', as: :log_out

  scope '/api' do
    resources :users, defaults: {format: 'json'}
  end

end

app/views/layouts/_businessnav.html.erb
<div class="fixed nav-div">
<nav class="top-bar nav-top-bar" data-topbar role="navigation">
  <ul class="title-area nav-bar-title">
    <li class="name sessions-index-title">
      <h1><a href="/sessions/business_index">GeoDeals</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active add-deal"><%= link_to "Add a Deal", deal_new_path(current_user.business_id) %></li>
      <li class="has-dropdown">
        <a href="#">User Mode</a>
        <ul class="dropdown">
          <li class="active"><%= link_to "User", sessions_path(current_user) %></a></li>
          <li class="active add-deal"><%= link_to "My Business", business_index_path(current_user.business_id) %></a></li>
        </ul>
      </li>
      <li class="active add-deal"></a></li>
      <li class="has-dropdown">
        <a href="#">Account</a>
        <ul class="dropdown">
          <li class="active add-deal"><%= link_to "Log Out", sessions_path, method: :delete %></a></li>
        </ul>
      </li>
    </ul>
  </section>
</nav>
</div>

app/views/layouts/_customernav.html.erb
<div class="fixed">
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name sessions-index-title">
      <h1><a href="/sessions">GeoDeals</a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right"> 
      <li class="active add-deal"><%= link_to "Log Out", sessions_path, method: :delete %></a>
      </li>
    </ul>
  </section>
</nav>
</div>

app/views/layouts/_nav.html.erb
<div class="fixed">
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">GeoDeals</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Add Deal</a></li>
      <li class="has-dropdown">
        <a href="#">Account</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
          <li class="active"><a href="#">Active link in dropdown</a></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul>
  </section>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    
    <%= Gon::Base.render_data({}) %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body ng-app="geoDeals">

    <% if @current_user %>
      <%# if @current_user.business_id == nil %>
        <div ui-view></div>
      <%# end %>
    <% end %>
    <%= yield %>

  </body>
</html>